services:
  db_pratica_ci-cd:
    image: postgres
    container_name: db_pratica_ci-cd
    restart: always #container reinicia se morrer
    ports:
      - 1234:5432
    env_file:
      - .env #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    volumes:
      - pg:/var/lib/postgresql/data

  node_app_pratica_ci-cd:
    container_name: node_app_pratica_ci-cd
    build: . #Dockerfile do node se encontra na pasta atual
    ports:
      - 5000:5000
    depends_on:
      - db_pratica_ci-cd # sรณ sobe quando o postgres tiver no ar
    env_file:
      - .env #configurar DATABASE_URL

volumes:
  pg: # volume para os postgres